apiVersion: v1
kind: Pod
metadata:
  name: anyname
  labels:
    app: anyapp
spec:
  containers:
    - name: anyname
      image: kammana/nodeapp:tagVersion
      ports:
        - containerPort: 8001
